UI rearrangement
dgtlrst/bit pull request #8
Opened 2024-08-09 16:06 UTC by TimMeiwald

2024-08-22 18:28 UTC, dgtlrst commented
@TimMeiwald here is my review:
1. Some file names are duplicating and it makes it a bit confusing which is what. For example, you have 3 file names, which contain the word `terminal`:
1. terminal_IO_tab.dart
2. terminal_settings_tab.dart
3. terminal.dart
It's not very clear what `terminal.dart` is responsible for: either put a comment inside the file or rename the file in the style of the rest two.

2. There is a general lack of comments in the code, it would be easier for other people to orient themselves in the code, if there were some comments here and there either around hard busingess logic or at creation/initialization of key elements.

3. Also - and if that's not too much of a bother - please mark clearly (can do with a comment again), the interface to the core rust library which the backend will be providing (e.g this currently happens to be `main()` routine of `TerminalRunner` class.

2024-08-23 11:44 UTC, dgtlrst commented
Additionally, @TimMeiwald, when i built the project with flutter, it notified me that there exist issues that can be fixed with the command `flutter fix`.

2024-08-23 11:45 UTC, dgtlrst commented
Also, there are dependencies with old versions and it complains about it. Check if some of them can be updated, including `flutter_to_rust_bridge`

2024-08-23 11:46 UTC, dgtlrst commented on lib/home.dart
> +  // return Expanded(child: grid);
remove unused commented code if it is not needed

2024-08-23 11:46 UTC, dgtlrst commented on lib/settings.dart
>  import 'sidepanel.dart'; // side panel
this comment is kinda unnecessary

2024-08-23 11:48 UTC, dgtlrst commented on rust/Cargo.toml
>  flutter_rust_bridge = "=2.1.0"
i am getting an error from rust_analyzer here, saying we are 2 minor versions behind latest (2.3.0), would it be breaking changes if we updated this?

2024-08-23 11:49 UTC, dgtlrst commented on rust/src/api/serial.rs
> +    }
where are these methods used and what are they needed for?

2024-08-23 11:50 UTC, dgtlrst requested changes
here are some comments

2024-08-23 20:27 UTC, TimMeiwald commented on rust/src/api/serial.rs
> +    }
They're used to serialize the port settings so I can save them using the shared_preferences lib that uses the platform specific app directory to save data. It's used in state_persistent_datastore.

2024-08-23 20:32 UTC, TimMeiwald commented on rust/Cargo.toml
>  flutter_rust_bridge = "=2.1.0"
Apparently not, I'll make a new commit

2024-08-23 21:25 UTC, closed without merging